name: Build Compose Multiplatform (Android & iOS)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Android APK
        run: ./gradlew assembleRelease

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: composeApp/build/outputs/apk/release/*.apk
          retention-days: 30

  build-ios:
    runs-on: macos-14  # Use macos-14 for better iOS 18 support

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate iOS Framework
        run: ./gradlew linkPodReleaseFrameworkIosArm64

      - name: Create exportOptions.plist
        run: |
          cd iosApp
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>thinning</key>
              <string>&lt;none&gt;</string>
          </dict>
          </plist>
          EOF

      - name: Build iOS Archive
        run: |
          cd iosApp
          
          # Check if workspace exists, otherwise use project
          if [ -f "iosApp.xcworkspace/contents.xcworkspacedata" ]; then
            PROJECT_TYPE="-workspace iosApp.xcworkspace"
            echo "Using workspace"
          elif [ -d "iosApp.xcodeproj" ]; then
            PROJECT_TYPE="-project iosApp.xcodeproj"
            echo "Using project"
          else
            echo "No Xcode workspace or project found"
            find . -name "*.xcodeproj" -o -name "*.xcworkspace"
            exit 1
          fi
          
          # Clean build directory
          rm -rf build/
          mkdir -p build/
          
          # Archive the project
          set -o pipefail && xcodebuild $PROJECT_TYPE \
                     -scheme iosApp \
                     -configuration Release \
                     -destination "generic/platform=iOS" \
                     -archivePath build/iosApp.xcarchive \
                     archive \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGN_IDENTITY="" \
                     PROVISIONING_PROFILE="" \
                     IPHONEOS_DEPLOYMENT_TARGET=12.0 \
                     SWIFT_OPTIMIZATION_LEVEL="-Onone" \
                     | xcpretty
          
          # Export archive to IPA
          xcodebuild -exportArchive \
                     -archivePath build/iosApp.xcarchive \
                     -exportPath build/ \
                     -exportOptionsPlist exportOptions.plist \
                     | xcpretty

      - name: List build outputs
        run: |
          echo "Build directory contents:"
          find iosApp/build -type f -name "*.ipa" || echo "No IPA found"
          ls -la iosApp/build/ || echo "No build directory"

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: |
            iosApp/build/*.ipa
            iosApp/build/iosApp.xcarchive
          retention-days: 30
        if: always()  # Upload even if previous steps had warnings

  commit-artifacts:
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: artifacts/android/

      - name: Download iOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: ios-ipa
          path: artifacts/ios/
        continue-on-error: true  # Don't fail if iOS build didn't produce artifacts

      - name: Create artifacts directory structure
        run: |
          mkdir -p artifacts/android artifacts/ios
          echo "Artifacts directory contents:"
          find artifacts/ -type f || echo "No artifacts found"

      - name: Add timestamp to artifacts
        run: |
          timestamp=$(date +'%Y%m%d_%H%M%S')
          
          # Process Android APKs
          cd artifacts/android
          for file in *.apk; do
            if [ -f "$file" ]; then
              mv "$file" "${file%.*}_${timestamp}.apk"
              echo "Renamed Android artifact: $file"
            fi
          done
          
          # Process iOS IPAs
          cd ../ios
          for file in *.ipa; do
            if [ -f "$file" ]; then
              mv "$file" "${file%.*}_${timestamp}.ipa"
              echo "Renamed iOS artifact: $file"
            fi
          done

      - name: Commit and push artifacts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Only add files if they exist
          if [ -n "$(find artifacts/ -name '*.apk' -o -name '*.ipa' 2>/dev/null)" ]; then
            git add artifacts/
          
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Add build artifacts - $(date +'%Y-%m-%d %H:%M:%S')"
              git push
            fi
          else
            echo "No artifacts to commit"
          fi