name: Build Compose Multiplatform (Android & iOS)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Android APK
        run: ./gradlew assembleRelease

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: composeApp/build/outputs/apk/release/*.apk
          retention-days: 30

  build-ios:
    runs-on: macos-latest  # Use latest macOS runner for best Xcode support

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Select Xcode version
        run: |
          # List available Xcode versions
          echo "Available Xcode versions:"
          ls /Applications/ | grep Xcode || echo "No Xcode apps found"
          
          # Try to find and use the highest available Xcode version
          LATEST_XCODE=$(ls /Applications/ | grep '^Xcode_' | sort -V | tail -1)
          
          if [ -n "$LATEST_XCODE" ]; then
            sudo xcode-select -s "/Applications/$LATEST_XCODE/Contents/Developer"
            echo "Using $LATEST_XCODE"
          elif [ -d "/Applications/Xcode.app" ]; then
            sudo xcode-select -s "/Applications/Xcode.app/Contents/Developer"
            echo "Using default Xcode.app"
          else
            echo "No Xcode installation found"
            exit 1
          fi
          
          # Show selected Xcode version
          echo "Selected Xcode path: $(xcode-select -p)"
          echo "Xcode version: $(xcrun xcodebuild -version)"

      - name: Fix Xcode Project Format Compatibility
        run: |
          cd iosApp
          
          # Check if project.pbxproj exists
          if [ -f "iosApp.xcodeproj/project.pbxproj" ]; then
            echo "Checking Xcode project format..."
          
            # Create a backup
            cp iosApp.xcodeproj/project.pbxproj iosApp.xcodeproj/project.pbxproj.backup
          
            # Try to fix the project format by changing it to a compatible version
            # Format 77 is Xcode 16, let's try to change it to format 60 (Xcode 15)
            sed -i '' 's/objectVersion = 77;/objectVersion = 60;/g' iosApp.xcodeproj/project.pbxproj
            sed -i '' 's/compatibilityVersion = "Xcode 16.0";/compatibilityVersion = "Xcode 15.0";/g' iosApp.xcodeproj/project.pbxproj
          
            echo "Modified project file to be compatible with Xcode 15"
          
            # Show the changes made
            echo "Changes made to project.pbxproj:"
            grep -E "objectVersion|compatibilityVersion" iosApp.xcodeproj/project.pbxproj || echo "No version strings found"
          else
            echo "project.pbxproj not found"
            ls -la iosApp.xcodeproj/
          fi

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: List available Gradle tasks
        run: ./gradlew tasks --all | grep -i ios || echo "No iOS tasks found, continuing..."

      - name: Build iOS Framework
        run: |
          # Try different possible task names for Compose Multiplatform
          if ./gradlew tasks --all | grep -q "linkReleaseFrameworkIosArm64"; then
            echo "Found linkReleaseFrameworkIosArm64 task"
            ./gradlew linkReleaseFrameworkIosArm64
          elif ./gradlew tasks --all | grep -q "assembleReleaseXCFramework"; then
            echo "Found assembleReleaseXCFramework task"
            ./gradlew assembleReleaseXCFramework
          elif ./gradlew tasks --all | grep -q "embedAndSignAppleFrameworkForXcode"; then
            echo "Found embedAndSignAppleFrameworkForXcode task"
            ./gradlew embedAndSignAppleFrameworkForXcode
          else
            echo "Building shared module for iOS"
            ./gradlew :shared:linkReleaseFrameworkIosArm64 || ./gradlew :composeApp:linkReleaseFrameworkIosArm64 || echo "Framework build step skipped"
          fi

      - name: Create exportOptions.plist
        run: |
          cd iosApp
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>thinning</key>
              <string>&lt;none&gt;</string>
          </dict>
          </plist>
          EOF

      - name: Build iOS Archive
        run: |
          cd iosApp
          
          # Debug: List directory contents
          echo "Current directory contents:"
          ls -la
          
          # Check if workspace exists, otherwise use project
          if [ -f "iosApp.xcworkspace/contents.xcworkspacedata" ]; then
            PROJECT_TYPE="-workspace iosApp.xcworkspace"
            echo "Using workspace: iosApp.xcworkspace"
          elif [ -d "iosApp.xcodeproj" ]; then
            PROJECT_TYPE="-project iosApp.xcodeproj"
            echo "Using project: iosApp.xcodeproj"
          else
            echo "No Xcode workspace or project found"
            echo "Available files:"
            find . -name "*.xcodeproj" -o -name "*.xcworkspace" -o -name "*.xcconfig"
            exit 1
          fi
          
          # Clean build directory
          rm -rf build/
          mkdir -p build/
          
          # Get available schemes
          echo "Available schemes:"
          xcodebuild $PROJECT_TYPE -list || echo "Could not list schemes"
          
          # Try to find the correct scheme name
          SCHEME_NAME="iosApp"
          if xcodebuild $PROJECT_TYPE -list 2>/dev/null | grep -q "GoMauris"; then
            SCHEME_NAME="GoMauris"
          fi
          
          echo "Using scheme: $SCHEME_NAME"
          
          # Archive the project
          set -o pipefail && xcodebuild $PROJECT_TYPE \
                     -scheme "$SCHEME_NAME" \
                     -configuration Release \
                     -destination "generic/platform=iOS" \
                     -archivePath build/iosApp.xcarchive \
                     archive \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGN_IDENTITY="" \
                     PROVISIONING_PROFILE="" \
                     DEVELOPMENT_TEAM="" \
                     IPHONEOS_DEPLOYMENT_TARGET=12.0 \
                     SWIFT_OPTIMIZATION_LEVEL="-Onone" \
                     COMPILER_INDEX_STORE_ENABLE=NO \
                     -allowProvisioningUpdates \
                     | xcpretty || {
                       echo "Archive failed, trying with different settings..."
                       xcodebuild $PROJECT_TYPE \
                         -scheme "$SCHEME_NAME" \
                         -configuration Release \
                         -destination "generic/platform=iOS" \
                         -archivePath build/iosApp.xcarchive \
                         archive \
                         CODE_SIGNING_ALLOWED=NO \
                         IPHONEOS_DEPLOYMENT_TARGET=12.0
                     }
          
          # Only try to export if archive succeeded
          if [ -d "build/iosApp.xcarchive" ]; then
            echo "Archive created successfully, attempting to export IPA..."
            xcodebuild -exportArchive \
                       -archivePath build/iosApp.xcarchive \
                       -exportPath build/ \
                       -exportOptionsPlist exportOptions.plist \
                       | xcpretty || echo "Export failed, but archive is available"
          else
            echo "Archive creation failed"
            exit 1
          fi

      - name: List build outputs
        run: |
          echo "Build directory contents:"
          find iosApp/build -type f -name "*.ipa" || echo "No IPA found"
          ls -la iosApp/build/ || echo "No build directory"

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: |
            iosApp/build/*.ipa
            iosApp/build/iosApp.xcarchive
          retention-days: 30
        if: always()  # Upload even if previous steps had warnings

  commit-artifacts:
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: artifacts/android/

      - name: Download iOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: ios-ipa
          path: artifacts/ios/
        continue-on-error: true  # Don't fail if iOS build didn't produce artifacts

      - name: Create artifacts directory structure
        run: |
          mkdir -p artifacts/android artifacts/ios
          echo "Artifacts directory contents:"
          find artifacts/ -type f || echo "No artifacts found"

      - name: Add timestamp to artifacts
        run: |
          timestamp=$(date +'%Y%m%d_%H%M%S')
          
          # Process Android APKs
          cd artifacts/android
          for file in *.apk; do
            if [ -f "$file" ]; then
              mv "$file" "${file%.*}_${timestamp}.apk"
              echo "Renamed Android artifact: $file"
            fi
          done
          
          # Process iOS IPAs
          cd ../ios
          for file in *.ipa; do
            if [ -f "$file" ]; then
              mv "$file" "${file%.*}_${timestamp}.ipa"
              echo "Renamed iOS artifact: $file"
            fi
          done

      - name: Commit and push artifacts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Only add files if they exist
          if [ -n "$(find artifacts/ -name '*.apk' -o -name '*.ipa' 2>/dev/null)" ]; then
            git add artifacts/
          
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Add build artifacts - $(date +'%Y-%m-%d %H:%M:%S')"
              git push
            fi
          else
            echo "No artifacts to commit"
          fi