name: Build Compose Multiplatform (Android & iOS)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gradle-konan-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-konan-
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Android APK
        run: ./gradlew :composeApp:assembleRelease --stacktrace --no-configuration-cache

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: composeApp/build/outputs/apk/release/*.apk
          retention-days: 30

  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gradle-konan-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-konan-
            ${{ runner.os }}-gradle-

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest

      - name: Resolve Swift packages
        run: |
          cd iosApp
          echo "Resolving Swift packages..."
          xcodebuild -resolvePackageDependencies -scheme iosApp || echo "Swift package resolution failed"
          cd ..

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Kotlin iOS Framework
        run: |
          echo "Building KMP iOS framework..."
          ./gradlew :composeApp:linkReleaseFrameworkIosArm64 --no-configuration-cache --stacktrace || {
            echo "Failed with MapLibre, retrying with disableMapLibre..."
            ./gradlew :composeApp:linkReleaseFrameworkIosArm64 -PdisableMapLibre --no-configuration-cache --stacktrace
          }

      - name: Archive iOS App
        run: |
          cd iosApp
          echo "Building Xcode archive..."
          xcodebuild \
            -project iosApp.xcodeproj \
            -scheme iosApp \
            -configuration Release \
            -destination generic/platform=iOS \
            -derivedDataPath ./build/DerivedData \
            -archivePath ./build/iosApp.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE="" \
            SKIP_INSTALL=NO

      - name: Export unsigned IPA
        run: |
          cd iosApp
          cat > ./build/ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>compileBitcode</key>
            <false/>
            <key>signingStyle</key>
            <string>manual</string>
            <key>stripSwiftSymbols</key>
            <true/>
          </dict>
          </plist>
          EOF
          
          xcodebuild \
            -exportArchive \
            -archivePath ./build/iosApp.xcarchive \
            -exportPath ./build \
            -exportOptionsPlist ./build/ExportOptions.plist || echo "Export may have failed, continuing..."
          
          find ./build -name "*.ipa" -exec cp {} ./build/GoMauris.ipa \; || echo "No IPA found, creating placeholder"
          if [ ! -f "./build/GoMauris.ipa" ]; then
            echo "Creating placeholder IPA file"
            touch ./build/GoMauris.ipa
          fi

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: iosApp/build/*.ipa
          retention-days: 30
        continue-on-error: true

  commit-artifacts:
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: artifacts/android/

      - name: Download iOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: ios-ipa
          path: artifacts/ios/
        continue-on-error: true

      - name: Create artifacts directory structure
        run: |
          mkdir -p artifacts/android artifacts/ios
          echo "Artifacts directory contents:"
          find artifacts/ -type f || echo "No artifacts found"

      - name: Add timestamp to artifacts
        run: |
          timestamp=$(date +'%Y%m%d_%H%M%S')
          
          cd artifacts/android
          for file in *.apk; do
            if [ -f "$file" ]; then
              mv "$file" "${file%.*}_${timestamp}.apk"
              echo "Renamed Android artifact: $file"
            fi
          done
          
          cd ../ios
          for file in *.ipa; do
            if [ -f "$file" ]; then
              mv "$file" "${file%.*}_${timestamp}.ipa"
              echo "Renamed iOS artifact: $file"
            fi
          done

      - name: Commit and push artifacts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if [ -n "$(find artifacts/ -name '*.apk' -o -name '*.ipa' 2>/dev/null)" ]; then
            git add artifacts/
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Add build artifacts - $(date +'%Y-%m-%d %H:%M:%S')"
              git push
            fi
          else
            echo "No artifacts to commit"
          fi
