name: Build Compose Multiplatform (Android & iOS)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gradle-konan-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-konan-
            ${{ runner.os }}-gradle-

      - name: Setup iOS build environment
        run: |
          # Install required tools
          which xcodebuild || echo "xcodebuild not found"
          which swift || echo "swift not found"
          
          # Create necessary directories for SPM
          mkdir -p ~/.konan
          
          # Check if Package.swift exists (SPM project indicator)
          if [ -f "Package.swift" ]; then
            echo "Found Package.swift, resolving Swift packages..."
            swift package resolve || echo "Swift package resolution failed"
          fi
          
          # Check for SPM in iOS app directory
          if [ -f "iosApp/Package.swift" ]; then
            echo "Found Package.swift in iosApp directory"
            cd iosApp
            swift package resolve || echo "Swift package resolution in iosApp failed"
            cd ..
          fi

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Android APK
        run: ./gradlew assembleRelease

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: composeApp/build/outputs/apk/release/*.apk
          retention-days: 30

  build-ios:
    runs-on: macos-latest  # Use macOS runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # ✅ Force stable Xcode version (avoids Xcode 26 beta issue)
      - name: Select stable Xcode (15.4)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Show Xcode version
        run: |
          echo "Xcode path: $(xcode-select -p)"
          xcodebuild -version
          xcrun simctl list runtimes

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build iOS Framework
        run: |
          ./gradlew clean
          ./gradlew :shared:linkReleaseFrameworkIosArm64 || \
          ./gradlew :composeApp:linkReleaseFrameworkIosArm64

      - name: Create exportOptions.plist
        run: |
          cd iosApp
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>thinning</key>
              <string>&lt;none&gt;</string>
          </dict>
          </plist>
          EOF

      - name: Build iOS Archive
        run: |
          cd iosApp
          rm -rf build/
          mkdir -p build/

          # Use project or workspace
          if [ -f "iosApp.xcworkspace/contents.xcworkspacedata" ]; then
            PROJECT_TYPE="-workspace iosApp.xcworkspace"
          else
            PROJECT_TYPE="-project iosApp.xcodeproj"
          fi

          SCHEME_NAME="iosApp"

          echo "Archiving with scheme: $SCHEME_NAME"
          set -o pipefail && xcodebuild $PROJECT_TYPE \
            -scheme "$SCHEME_NAME" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath build/iosApp.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO \
            IPHONEOS_DEPLOYMENT_TARGET=12.0 \
            | xcpretty

          # Export IPA if archive succeeded
          if [ -d "build/iosApp.xcarchive" ]; then
            xcodebuild -exportArchive \
              -archivePath build/iosApp.xcarchive \
              -exportPath build/ \
              -exportOptionsPlist exportOptions.plist \
              | xcpretty
          fi

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: |
            iosApp/build/*.ipa
            iosApp/build/iosApp.xcarchive
          retention-days: 30

  commit-artifacts:
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: artifacts/android/

      - name: Download iOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: ios-ipa
          path: artifacts/ios/
        continue-on-error: true  # Don't fail if iOS build didn't produce artifacts

      - name: Create artifacts directory structure
        run: |
          mkdir -p artifacts/android artifacts/ios
          echo "Artifacts directory contents:"
          find artifacts/ -type f || echo "No artifacts found"

      - name: Add timestamp to artifacts
        run: |
          timestamp=$(date +'%Y%m%d_%H%M%S')
          
          # Process Android APKs
          cd artifacts/android
          for file in *.apk; do
            if [ -f "$file" ]; then
              mv "$file" "${file%.*}_${timestamp}.apk"
              echo "Renamed Android artifact: $file"
            fi
          done
          
          # Process iOS IPAs
          cd ../ios
          for file in *.ipa; do
            if [ -f "$file" ]; then
              mv "$file" "${file%.*}_${timestamp}.ipa"
              echo "Renamed iOS artifact: $file"
            fi
          done

      - name: Commit and push artifacts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Only add files if they exist
          if [ -n "$(find artifacts/ -name '*.apk' -o -name '*.ipa' 2>/dev/null)" ]; then
            git add artifacts/
          
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Add build artifacts - $(date +'%Y-%m-%d %H:%M:%S')"
              git push
            fi
          else
            echo "No artifacts to commit"
          fi